export const COMPARISONS = [
  {
    title: "Against Government and Official Regulatory Bodies",
    content: "Traditional government registries like IP India and the Copyright Office operate on a slow, manual cadence that routinely takes 12 to 24 months to offer brand protection. Furthermore, entities like the Controller of Certifying Authorities (CCA) only validate the identity of the signer through digital signatures, without checking the content's digital structure or authenticity. ProofStamp elevates this process by functioning as an instant, pre-filing verification network. Instead of waiting months, users secure immediate, cryptographically sound prior use evidence within seconds. Unlike the Copyright Office, which merely logs a static ownership claim without verifying digital integrity, ProofStamp acts as a forensic anchor — actively validating file structural metrics while filling the market vacancy left by legacy platforms like the discontinued WIPO PROOF."
  },
  {
    title: "Against Digital Signature and Legal Workflow Platforms",
    content: "Prominent Indian workflow platforms like Leegality and NeSL excel at establishing compliance audit trails for corporate agreements and text affidavits. Similarly, certifying authorities like eMudhra and Capricorn sell the secure cryptographic pen — the USB token or identity certificate itself. However, these systems are fundamentally limited to document execution and fail to protect creative media. ProofStamp outperforms these tools by protecting the actual assets — raw images, source code, audio, and video — rather than just the accompanying contracts. While existing platforms provide the raw identity tools, ProofStamp provides the actual forensic preservation vault, mapping secure user identity directly to specific content structures."
  },
  {
    title: "Against Digital Forensic and Preservation Tools",
    content: "Post-incident software like Hunchly and PageFreezer allows investigators to capture external web pages as evidence after a legal dispute has already begun. PageFreezer's value is in historical archiving, not point-in-time certification, and its enterprise contract cost and onboarding complexity make it a poor fit for individual law firms or solo professionals. Hunchly is a Chrome extension built for OSINT analysts capturing web pages during active investigations — it produces a session archive, not a creator's forensic timestamp sealed before the crime occurred. On the enterprise side, physical labs like Truth Labs perform manual, highly expensive hardware analysis to reconstruct timelines for court proceedings. ProofStamp flips this reactive paradigm entirely — the seal is placed before publication, before the crime, converting a reactive forensic workflow into a proactive evidentiary posture that no post-incident tool can replicate retroactively."
  },
  {
    title: "Against Blockchain Timestamping and IP Registries",
    content: "Platforms such as Bernstein.io, OriginStamp, and WordProof leverage public ledger frameworks to record raw data hashes on the blockchain — and while these systems offer secure decentralization, they provide little utility in a courtroom because a bare cryptographic hash string confuses judges and legal advocates alike. Neither platform generates a BSA 2023 Section 63 compliant System Certificate, neither embeds a DWT-DCT watermark creating a forensic link inside the file itself, and neither binds the creator's government-verified identity to the timestamp record. ProofStamp bridges this technical gap by converting complex hashes into automated, legally compliant Counsel Evidence Packs — documentation that a lawyer can open, read, and present without a cryptography PhD, which is the actual product the legal market will pay for."
  },
  {
    title: "Against Deep-Tech Invisible Watermarking and DRM Providers",
    content: "Global infrastructure giants like Digimarc, NexGuard, and Verance provide robust pixel and audio watermarking, but they build these platforms exclusively for Hollywood studios, major streaming services, and large supply chains. Digimarc is a 30-year-old NASDAQ-listed enterprise whose watermarking technology protects global currency — in a notable deployment, it partnered with a consortium of the world's central banks to deter counterfeiting — infrastructure designed for institutions, not independent creators. A stock photographer in Indore cannot call Digimarc's sales team and get a deployment contract. There is no self-serve onboarding, no ₹99 tier, and no BSA Section 63 compliant certificate automatically generated at the end of the workflow. ProofStamp takes the same frequency-domain watermarking architecture Digimarc sells to central banks and delivers it as a 10-second self-serve cloud tool built specifically for India's legal and pricing reality."
  },
  {
    title: "Against Online Legal Aggregators",
    content: "Tech platforms like Trademarkia, IndiaFilings, and VakilSearch focus strictly on high-volume form submission, drawing direct scrutiny from regulatory authorities for offering unauthorized representation. The CGPDTM's January 7, 2026 public notice explicitly named platforms including indiafilings.com and corpbiz.io for unauthorized solicitation of trademark services in violation of the Advocates Act 1961 and the Trade Marks Act 1999 — formally censured by the very government authority whose approval ProofStamp's architecture is specifically engineered to satisfy. These services file applications without verifying the underlying priority dates or technical ownership roots of a brand, which frequently results in official rejections. ProofStamp does not practice law, does not file applications, and does not represent clients before any registry. It builds the evidentiary foundation that a licensed advocate then uses — putting ProofStamp on the correct side of the exact regulatory line these platforms crossed."
  },
  {
    title: "Against Media Provenance and Camera Authenticity Tools",
    content: "Hardware-driven initiatives by Sony and Leica embed C2PA metadata directly into high-end camera sensors at the point of capture, while software platforms like Truepic, Attestiv, and Numbers Protocol validate raw media authenticity to combat AI deepfakes. Truepic Vision requires the photo to be taken inside the Truepic app itself at the moment of capture — meaning it cannot protect any existing creative file, any legacy image, any source code, or any document created before a dispute arises. Numbers Protocol's native token has lost over 95% of its value since peak and its ecosystem activity is in measurable decline by on-chain metrics — it is a Web3 product solving a Web3 problem that Indian courts have not yet been asked to accept. Hardware tracking more broadly fails to protect legacy files, corporate documents, graphic designs, or generative software assets. ProofStamp provides a hardware-agnostic alternative that protects any digital file format across its entire lifecycle, regardless of the device used to create it, and produces documentation that a Section 79A notified government examiner has already certified as technically sound."
  },
  {
    title: "Against Adobe Content Credentials",
    content: "Adobe Content Credentials, now mandatory across Firefly and Creative Cloud as of early 2026, are an excellent provenance signal — but C2PA metadata is stripped when images are shared on platforms that reprocess files through compression, resizing, or format conversion, meaning the provenance chain breaks at the exact moment of distribution where infringement most commonly occurs. The RAND Corporation's June 2025 analysis explicitly warned that C2PA's success depends on end-to-end compliance by all elements of the ecosystem — and in an open internet, that compliance does not exist. C2PA signing certificates start at approximately $289 per year with no free alternative, creating an immediate accessibility gap for India's 4 million independent creators. ProofStamp's DWT-DCT watermark is embedded inside the file's pixel structure — it survives the compression, resizing, and platform reprocessing that destroys C2PA metadata entirely — and is available from ₹99 per month."
  },
  {
    title: "Against the Discontinued WIPO PROOF",
    content: "WIPO PROOF was the closest global analog to ProofStamp — a UN-backed timestamping service for intellectual property assets that was shut down in 2020 citing unsustainable operational costs, leaving a verified market vacancy that no Indian platform has filled at affordable pricing. ProofStamp is the only platform currently positioned to fill this gap within India's specific BSA 2023 and IT Act 2000 Section 79A legal framework — with the added layers WIPO PROOF never offered: perceptual fingerprinting, invisible watermarking, blockchain anchoring, and automated DMCA letter generation. Where WIPO PROOF produced a timestamped receipt, ProofStamp produces a complete Counsel Evidence Pack that is immediately actionable in Indian proceedings without additional legal interpretation."
  },
  {
    title: "Against Asset Management and Brand Protection Networks",
    content: "Enterprise platforms like Adobe Experience Manager and Bynder manage large internal media libraries, while web-monitoring networks like Corsearch, Incopro, and MarqVision scan public marketplaces to discover counterfeit goods after they appear. Despite their expansive capabilities, tracking tools only notice brand theft after the damage is done, and asset managers lack automated legal generation modules. ProofStamp operates as the essential foundational layer that sits beneath these networks — focused entirely on engineering the immutable core evidence and automated Counsel Evidence Packets required to power legal takedowns. When monitoring tools discover an asset violation, ProofStamp ensures your legal team already holds the precise digital proof needed to act immediately."
  }
];
